/**
 * Nonce utilities for CSP integration
 * 
 * This module provides a way to access the CSP nonce generated by middleware
 * for use in server components and MUI's cache provider.
 */

import { headers } from 'next/headers';

/**
 * Get the CSP nonce from the request headers
 * This must be called from a server component or server action
 */
export async function getNonce(): Promise<string | undefined> {
    const headersList = await headers();
    return headersList.get('x-nonce') ?? undefined;
}
