export const AGENT_CAPABILITY_RUNGS = {
  READ: 0,
  INGEST: 1,
  COMMENT: 2,
  PROPOSE: 3,
  WRITE_SINGLE: 4,
  WRITE_GROUP: 5,
  BULK: 6,
  PROPOSE_EXTERNAL: 7,
  EXECUTE_EXTERNAL: 8,
} as const;

export const MAX_AGENT_CAPABILITY_RUNG =
  AGENT_CAPABILITY_RUNGS.EXECUTE_EXTERNAL;
export const DEFAULT_AGENT_ENABLED_RUNGS = [
  AGENT_CAPABILITY_RUNGS.READ,
  AGENT_CAPABILITY_RUNGS.INGEST,
  AGENT_CAPABILITY_RUNGS.COMMENT,
  AGENT_CAPABILITY_RUNGS.PROPOSE,
];

export const DEFAULT_SUGGESTION_TTL_DAYS = 30;
